et.TEAM_NONE       = 0
et.TEAM_AXIS       = 1
et.TEAM_ALLIES     = 2
et.TEAM_SPEC       = 3
et.CLASS_SOLDIER   = 0
et.CLASS_MEDIC     = 1
et.CLASS_ENGINEER  = 2
et.CLASS_FIELDOPS  = 3
et.CLASS_COVERTOPS = 4
et.SKILL_SENSE     = 0
et.SKILL_ENGINEER  = 1
et.SKILL_MEDIC     = 2
et.SKILL_SIGNAL    = 3
et.SKILL_LIGHT     = 4
et.SKILL_HEAVY     = 5
et.SKILL_COVERT    = 6

et.TEAM = { }
et.TEAM[et.TEAM_NONE]   = "None"
et.TEAM[et.TEAM_AXIS]   = "Axis"
et.TEAM[et.TEAM_ALLIES] = "Allies"
et.TEAM[et.TEAM_SPEC]   = "Spectator"
et.TEAM_SHORT = { }
--et.TEAM_SHORT[et.TEAM_NONE]   = ""
et.TEAM_SHORT[et.TEAM_AXIS]   = "r"
et.TEAM_SHORT[et.TEAM_ALLIES] = "b"
et.TEAM_SHORT[et.TEAM_SPEC]   = "s"

et.CLASS = { }
et.CLASS[et.CLASS_SOLDIER]   = "Soldier"
et.CLASS[et.CLASS_MEDIC]     = "Medic"
et.CLASS[et.CLASS_ENGINEER]  = "Engineer"
et.CLASS[et.CLASS_FIELDOPS]  = "Field Ops"
et.CLASS[et.CLASS_COVERTOPS] = "Covert Ops"

et.SKILL = { }
et.SKILL[et.SKILL_SENSE]    = "Battle Sense"
et.SKILL[et.SKILL_ENGINEER] = "Engineer"
et.SKILL[et.SKILL_MEDIC]    = "Medic"
et.SKILL[et.SKILL_SIGNAL]   = "Signals"
et.SKILL[et.SKILL_LIGHT]    = "Light Weapons"
et.SKILL[et.SKILL_HEAVY]    = "Heavy Weapons"
et.SKILL[et.SKILL_COVERT]   = "Covert Ops"

zapi.COUNTRY = {
	"Asia/Pacific Region",
	"Europe",
	"Andorra",
	"United Arab Emirates",
	"Afghanistan",
	"Antigua and Barbuda",
	"Anguilla",
	"Albania",
	"Armenia",
	"Netherlands Antilles",
	"Angola",
	"Antarctica",
	"Argentina",
	"American Samoa",
	"Austria",
	"Australia",
	"Aruba",
	"Azerbaijan",
	"Bosnia and Herzegovina",
	"Barbados",
	"Bangladesh",
	"Belgium",
	"Burkina Faso",
	"Bulgaria",
	"Bahrain",
	"Burundi",
	"Benin",
	"Bermuda",
	"Brunei Darussalam",
	"Bolivia",
	"Brazil",
	"Bahamas",
	"Bhutan",
	"Bouvet Island",
	"Botswana",
	"Belarus",
	"Belize",
	"Canada",
	"Cocos (Keeling) Islands",
	"Congo-Kinshasa",
	"Central African Republic",
	"Congo-Brazzaville",
	"Switzerland",
	"Cote D'Ivoire",
	"Cook Islands",
	"Chile",
	"Cameroon",
	"China",
	"Colombia",
	"Costa Rica",
	"Cuba",
	"Cape Verde",
	"Christmas Island",
	"Cyprus",
	"Czech Republic",
	"Germany",
	"Djibouti",
	"Denmark",
	"Dominica",
	"Dominican Republic",
	"Algeria",
	"Ecuador",
	"Estonia",
	"Egypt",
	"Western Sahara",
	"Eritrea",
	"Spain",
	"Ethiopia",
	"Finland",
	"Fiji",
	"Falkland Islands (Malvinas)",
	"Micronesia",
	"Faroe Islands",
	"France",
	"France, Metropolitan",
	"Gabon",
	"United Kingdom",
	"Grenada",
	"Georgia",
	"French Guiana",
	"Ghana",
	"Gibraltar",
	"Greenland",
	"Gambia",
	"Guinea",
	"Guadeloupe",
	"Equatorial Guinea",
	"Greece",
	"South Georgia and the South Sandwich Islands",
	"Guatemala",
	"Guam",
	"Guinea-Bissau",
	"Guyana",
	"Hong Kong",
	"Heard Island and McDonald Islands",
	"Honduras",
	"Croatia",
	"Haiti",
	"Hungary",
	"Indonesia",
	"Ireland",
	"Israel",
	"India",
	"British Indian Ocean Territory",
	"Iraq",
	"Iran",
	"Iceland",
	"Italy",
	"Jamaica",
	"Jordan",
	"Japan",
	"Kenya",
	"Kyrgyzstan",
	"Cambodia",
	"Kiribati",
	"Comoros",
	"Saint Kitts and Nevis",
	"North Korea",
	"South Korea",
	"Kuwait",
	"Cayman Islands",
	"Kazakhstan",
	"Laos",
	"Lebanon",
	"Saint Lucia",
	"Liechtenstein",
	"Sri Lanka",
	"Liberia",
	"Lesotho",
	"Lithuania",
	"Luxembourg",
	"Latvia",
	"Libya",
	"Morocco",
	"Monaco",
	"Moldova",
	"Madagascar",
	"Marshall Islands",
	"Macedonia",
	"Mali",
	"Burma",
	"Mongolia",
	"Macau",
	"Northern Mariana Islands",
	"Martinique",
	"Mauritania",
	"Montserrat",
	"Malta",
	"Mauritius",
	"Maldives",
	"Malawi",
	"Mexico",
	"Malaysia",
	"Mozambique",
	"Namibia",
	"New Caledonia",
	"Niger",
	"Norfolk Island",
	"Nigeria",
	"Nicaragua",
	"Netherlands",
	"Norway",
	"Nepal",
	"Nauru",
	"Niue",
	"New Zealand",
	"Oman",
	"Panama",
	"Peru",
	"French Polynesia",
	"Papua New Guinea",
	"Philippines",
	"Pakistan",
	"Poland",
	"Saint Pierre and Miquelon",
	"Pitcairn Islands",
	"Puerto Rico",
	"Palestinian Territory",
	"Portugal",
	"Palau",
	"Paraguay",
	"Qatar",
	"Reunion",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saudi Arabia",
	"Solomon Islands",
	"Seychelles",
	"Sudan",
	"Sweden",
	"Singapore",
	"Saint Helena",
	"Slovenia",
	"Svalbard and Jan Mayen",
	"Slovakia",
	"Sierra Leone",
	"San Marino",
	"Senegal",
	"Somalia",
	"Suriname",
	"Sao Tome and Principe",
	"El Salvador",
	"Syria",
	"Swaziland",
	"Turks and Caicos Islands",
	"Chad",
	"French Southern Territories",
	"Togo",
	"Thailand",
	"Tajikistan",
	"Tokelau",
	"Turkmenistan",
	"Tunisia",
	"Tonga",
	"Timor-Leste",
	"Turkey",
	"Trinidad and Tobago",
	"Tuvalu",
	"Taiwan",
	"Tanzania",
	"Ukraine",
	"Uganda",
	"United States Minor Outlying Islands",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Holy See (Vatican City State)",
	"Saint Vincent and the Grenadines",
	"Venezuela",
	"Virgin Islands, British",
	"Virgin Islands, U.S.",
	"Vietnam",
	"Vanuatu",
	"Wallis and Futuna",
	"Samoa",
	"Yemen",
	"Mayotte",
	"Serbia",
	"South Africa",
	"Zambia",
	"Montenegro",
	"Zimbabwe",
	"Hoombaweigh",
	"Satellite Provider",
	"Other",
	"Aland Islands",
	"Guernsey",
	"Isle of Man",
	"Jersey",
	"Saint Barthelemy",
	"Saint Martin"
}

zapi.color = {
	["BLACK"]           = "^0" , 
	["BLUE"]            = "^4" , 
	["BROWN"]           = "^K" , 
	["BROWN_ALT"]       = "^+" , 
	["CYAN"]            = "^5" , 
	["DARK_GREEN"]      = "^H" , 
	["DARK_PURPLE"]     = "^C" , 
	["DARK_RED"]        = "^J" , 
	["DARK_RED_ALT"]    = "^?" , 
	["DARK_TAN"]        = "^M" , 
	["DARK_TAN_ALT"]    = "^-" , 
	["GREEN"]           = "^2" , 
	["GREY"]            = "^9" , 
	["LIGHT_BLUE"]      = "^F" , 
	["LIGHT_BLUE_ALT"]  = "^D" , 
	["LIGHT_BROWN"]     = "^L" , 
	["LIGHT_BROWN_ALT"] = "^@" , 
	["LIGHT_GREY"]      = "^Z" , 
	["LIGHT_ORANGE"]    = "^A" , 
	["LIGHT_RED"]       = "^I" , 
	["LIGHT_TAN"]       = "^/" , 
	["ORANGE"]          = "^8" , 
	["PALE_GREEN"]      = "^G" , 
	["PALE_YELLOW"]     = "^O" , 
	["PINK"]            = "^6" , 
	["PURPLE"]          = "^E" , 
	["RED"]             = "^1" , 
	["TAN"]             = "^N" , 
	["TURQUOISE"]       = "^B" , 
	["WHITE"]           = "^7" , 
	["YELLOW"]          = "^3",
}